In [7]:
import sys
import numpy as np

In [8]:
#Basic Numpy Arrays

In [9]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [10]:
a = np.array([1,2,3,4])

In [11]:
b = np.array([0,.5,1,1.5,2])

In [13]:
a[0], a[1]

(1, 2)

In [14]:
a[0:]

array([1, 2, 3, 4])

In [15]:
a[1:3]

array([2, 3])

In [16]:
a[1:-1]

array([2, 3])

In [17]:
a[::2]

array([1, 3])

In [20]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [21]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [22]:
#Array Types

In [23]:
a

array([1, 2, 3, 4])

In [24]:
a.dtype

dtype('int64')

In [25]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [26]:
b.dtype

dtype('float64')

In [28]:
np.array([1, 2, 3, 4], dtype=np.float)

/var/folders/px/rv4mh3xn46z7059z336yx46r0000gn/T/ipykernel_957/217965920.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [29]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [30]:
c= np.array(['a','b','c'])

In [31]:
c.dtype

dtype('<U1')

In [33]:
d = np.array([{'a': 1}, sys])

In [34]:
d.dtype

dtype('O')

In [35]:
#Dimension and shapes

In [36]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [37]:
A.shape  #dos filas tres columnas

(2, 3)

In [38]:
A.ndim

2

In [39]:
A.size

6

In [41]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [42]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [43]:
B.shape

(2, 2, 3)

In [44]:
B.ndim

3

In [45]:
B.size

12

In [46]:
C = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4]
        
    ]
])

/var/folders/px/rv4mh3xn46z7059z336yx46r0000gn/T/ipykernel_957/3201812546.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [47]:
C.dtype

dtype('O')

In [48]:
C.shape

(2,)

In [49]:
C.size

2

In [50]:
type(C[0])

list

In [51]:
#indexing and Slicing of matrices

In [64]:
#Square matrix
A = np.array([
    
#C   0 1 2
    
    [1,2,3], #F 0
    [4,5,6], #F 1
    [7,8,9]  #F 2
])

In [65]:
A[1]

array([4, 5, 6])

In [66]:
A[1][0]

4

In [55]:
A[1, 0]

4

In [56]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [58]:
A[:2, 2:]

array([[3],
       [6]])

In [59]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
A[1] = np.array([10,10,10])

In [61]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [62]:
A[2] = 99

In [63]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [67]:
#Summary statics

In [68]:
a = np.array([1,2,3,4])

In [69]:
a.sum()

10

In [70]:
a.mean()

2.5

In [71]:
a.std()

1.118033988749895

In [72]:
a.var()

1.25

In [74]:
A = np.array([[ 1, 2, 3],
              [ 4, 5, 6],
              [ 7, 8, 9]
          ])

In [75]:
A.sum()

45

In [76]:
A.mean()

5.0

In [77]:
A.std()

2.581988897471611

In [78]:
A.sum(axis=0)  #columna

array([12, 15, 18])

In [79]:
A.sum(axis=1) #fila

array([ 6, 15, 24])

In [80]:
A.mean(axis=0)  #columna

array([4., 5., 6.])

In [81]:
A.mean(axis=1)  #fila

array([2., 5., 8.])

In [82]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [84]:
A.std(axis=1)  #y mas.....

array([0.81649658, 0.81649658, 0.81649658])

In [85]:
#Broadcasting and vectorized operations

In [86]:
a = np.arange(4)

In [87]:
a

array([0, 1, 2, 3])

In [88]:
a + 10

array([10, 11, 12, 13])

In [89]:
a * 10

array([ 0, 10, 20, 30])

In [90]:
a

array([0, 1, 2, 3])

In [91]:
a += 100

In [92]:
a

array([100, 101, 102, 103])

In [94]:
l = [0,1,2,3]

In [95]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [96]:
a = np.arange(4)

In [97]:
a

array([0, 1, 2, 3])

In [98]:
b = np.array([10,10,10,10])

In [99]:
b

array([10, 10, 10, 10])

In [100]:
a + b

array([10, 11, 12, 13])

In [101]:
a * b

array([ 0, 10, 20, 30])

In [103]:
#Boolean arrays Tambien llamados masks

In [104]:
a = np.arange(4)

In [105]:
a

array([0, 1, 2, 3])

In [106]:
a[0], a[-1]

(0, 3)

In [107]:
a[[0, -1]]

array([0, 3])

In [108]:
a[[True, False, False, True]]

array([0, 3])

In [109]:
a

array([0, 1, 2, 3])

In [110]:
a >= 2

array([False, False,  True,  True])

In [111]:
a[a >= 2]

array([2, 3])

In [112]:
a.mean()

1.5

In [113]:
a[a > a.mean()]

array([2, 3])

In [114]:
a[~(a > a.mean())]

array([0, 1])

In [115]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [116]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [117]:
A = np.random.randint(100, size=(3, 3))

In [118]:
A

array([[76, 27, 83],
       [87, 86, 32],
       [84, 25, 12]])

In [119]:
A[np.array([
    [True, False, True],
    [False, False, False],
    [True, False, True]
])]

array([76, 83, 84, 12])

In [120]:
A > 36

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False, False]])

In [121]:
A[A > 36]

array([76, 83, 87, 86, 84])

In [122]:
#Linear Algebra

In [123]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [124]:
B = np.array([
     [6,5],
     [4,3],
     [2,1]
])

In [125]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [126]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [128]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [129]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [131]:
#Size of objects in memory

In [132]:
#Int, floats

In [133]:
#An integer in python is > 24bytes
sys.getsizeof(1)

28

In [134]:
# Long are even larger
sys.getsizeof(10**100)

72

In [135]:
#Numpy size is much smaller
np.dtype(int).itemsize

8

In [136]:
#Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [137]:
np.dtype(float).itemsize

8

In [138]:
#List are even larger

In [139]:
#A one element list
sys.getsizeof([1])

64

In [140]:
#An array of one element in numpy
np.array([1]).nbytes

8

In [141]:
#And performance is also important

In [142]:
l = list(range(100000))

In [143]:
a = np.sum(a**2)

In [144]:
%time np.sum(a ** 2)

CPU times: user 198 µs, sys: 2 µs, total: 200 µs
Wall time: 209 µs


196

In [145]:
%time np.sum(a ** 2 for x in l)

CPU times: user 17.7 ms, sys: 520 µs, total: 18.3 ms
Wall time: 18.2 ms


<timed eval>:1: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.


19600000

In [146]:
#Useful Numpy functions

In [ ]:
#random

In [147]:
np.random.random(size=2)

array([0.6239795, 0.1296134])

In [148]:
np.random.normal(size=2)

array([-1.48658893, -1.13550364])

In [149]:
np.random.rand(2,4)

array([[0.42673278, 0.73655583, 0.59109139, 0.61525847],
       [0.88679365, 0.30569757, 0.17923765, 0.68330661]])

In [150]:
#arange

In [151]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [153]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [154]:
#reshape

In [155]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [156]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#linspace

In [157]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [158]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [159]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [160]:
#zeros,ones,empty

In [161]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [164]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [165]:
np.zeros((3, 3), dtype=np.int)

/var/folders/px/rv4mh3xn46z7059z336yx46r0000gn/T/ipykernel_957/383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [166]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [167]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [168]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [169]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [170]:
#identity and eye

In [171]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [172]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [173]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [174]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [175]:
np.eye(8,4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])